### ISSUE TITLE
看板 api 加年份參數

### ISSUE THREAD

**Issue by yeefun** [readr-media/election-boards#67]
資料頁有一個頁面是可以看到同一地點的其它看板，它打的 api  是 `http://dev.readr.tw/project/election-boards/api/boards/`，並用 `coordinates` 這個參數去做篩選，不過因為這個 api 沒有年份可篩選，所以它會連 2018 年的看板也一併呈現出來。

希望這個 api 可以增加年份（`election_year`）的參數以供篩選。

**Comment by yeefun** [comment]
http://dev.readr.tw/project/election-boards/api/boards?election_year=2020

**Comment by ichiaohsu** [comment]
Merged commits will auto close this issue. Please leave there if there are real modifications but not yet merged into master.

**Comment by yeefun** [comment]
抱歉，打開了，下次會注意。
