### ISSUE TITLE
上傳頁面 slogan、board_type 改成非必填。

### ISSUE THREAD

**Issue by yeefun** [readr-media/election-boards#70]
目前在上傳頁面上傳看板，標語（`slogan`）和看板類型（`board_type`）在後端是必填的，如果不填，就會回`{"error":{"board_type":["This field may not be blank."],"slogan":["This field may not be blank."]}}`，看板就上傳不上去。

我問了又如，他希望這兩個都不要是必填的，上一次似乎也沒有必填。因此希望可以把這兩個欄位在後端變成非必填。

**Comment by ichiaohsu** [comment]
It seems there is no restrictions on those two field in database level. What's the method you use to insert the board?

**Comment by yeefun** [comment]
api
`http://dev.readr.tw/project/election-boards/api/boards/`

payload:
```
{
  "candidates": [
    98392
  ],
  "took_at": 1571986053,
  "uploaded_by": "b4dfd117-47b3-47b5-b706-ae584dfbc359",
  "coordinates": "(25.050967283299258 121.56051166715089)",
  "image": "/proj-assets/election-board/uploads/images/1571986062-367ddd7b0f1c480c8629504aa7fecdd9.jpg",
  "county": "台北市",
  "district": "松山區",
  "road": "南京東路五段66巷2弄1-1號",
  "uploader_name": "",
  "slogan": "",
  "party_icon": false,
  "board_type": ""
}
```

我在你提供的 http://dev.readr.tw/project/election-boards/api/docs/ 試用上面的 payload，也是會出現以下錯誤訊息：
```
{
  "board_type": [
    "This field may not be blank."
  ],
  "slogan": [
    "This field may not be blank."
  ]
}
```

@ichiaohsu

**Comment by ichiaohsu** [comment]
On `slogan` and `board_type` you pass empty string. If you do not pass in those two fields it will be ok. I guess it's fine if you don't send these two fields, but if you pass in two empty string it's not allowed.

@yeefun
